# Generated by Django 3.0.4 on 2020-04-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.Location')),
            ],
        ),
    ]
