# Generated by Django 3.0.4 on 2020-04-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.IntegerField(choices=[(1, 'Ceslius'), (2, 'Humidity'), (3, 'Lumen'), (4, 'Moisture')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=16)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.Probe')),
            ],
        ),
    ]
