# Generated by Django 3.0.4 on 2020-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0004_auto_20200402_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='User',
            new_name='user',
        ),
    ]
