# Generated by Django 3.0.4 on 2020-05-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_logger', '0005_auto_20200414_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=32)),
                ('prop', models.IntegerField(choices=[(1, 'Temperature'), (2, 'Humidity'), (3, 'Brightness'), (4, 'Moisture')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('sensors', models.ManyToManyField(to='data_logger.Sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
                'index_together': {('user', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='data_logger.Sensor'),
        ),
        migrations.DeleteModel(
            name='Probe',
        ),
    ]
