# Generated by Django 3.0.4 on 2020-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0006_auto_20200521_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='probe',
            new_name='sensor',
        ),
    ]
